### ISSUE TITLE
GitHub Pages not on

### ISSUE THREAD

**Issue by neilmispelaar** [irm1005-itec1005-fall-2023/assignment-03-thisfeelsimpossible#2]
Hey @thisfeelsimpossible - your GitHub Pages Web Server hasn't been turned on

**Comment by thisfeelsimpossible** [comment]
did it not go through?!?!?! i just committed like 10 mins ago

**Comment by neilmispelaar** [comment]
You correctly turned on GitHub Pages - that’s why I closed the issue.
